name: projects
description: A Flutter app with a bottom navigation bar.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_svg: ^1.0.0
  cupertino_icons: ^1.0.8
  flutter_inappwebview: ^6.1.5 # For rendering the webview in the Internet screen.
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  animate_do: ^3.1.2
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/background.png
    - assets/illustration.png

